const $=(id)=>document.getElementById(id);
const els={message:$('messageInput'),check:$('checkButton'),result:$('resultCard'),banner:$('riskBanner'),riskIcon:$('riskIcon'),riskLabel:$('riskLabel'),riskSummary:$('riskSummary'),riskScore:$('riskScore'),warnings:$('warningList'),actions:$('actionList'),language:$('languageSelect'),status:$('uploadStatus'),preview:$('imagePreview'),file:$('fileInput'),voice:$('voiceButton'),read:$('readButton'),trusted:$('trustedButton'),copy:$('copyButton'),toast:$('toast')};
let lastResult=null;let recognition=null;let sampleIndex=0;
const translations={
 en:{pageTitle:'Is this message safe?',pageSubtitle:'Paste a suspicious text, email, or social-media message. SafeCircle will explain the warning signs in plain language.',missionText:'Accessible scam protection',languageLabel:'Language',settingsButton:'Trusted person',inputTitle:'Add the suspicious message',sampleButton:'Try an example',messageLabel:'Message text',privacyNote:'Your message is analyzed on this device and is not saved.',voiceButton:'🎙 Speak message',uploadButton:'📷 Upload screenshot',clearButton:'Clear',checkButton:'Check this message',resultHeading:'Your safety check',signsHeading:'Warning signs found',actionsHeading:'What to do now',readButton:'🔊 Read result aloud',trustedButton:'Ask my trusted person',copyButton:'Copy safety report',disclaimer:'SafeCircle provides guidance, not a guarantee. Contact an organization using a phone number or website you find independently.',learnTitle:'Pause before you act',tip1Title:'Slow down',tip1Text:'Scammers create urgency so you act before thinking.',tip2Title:'Protect codes',tip2Text:'Never share a password, PIN, or one-time verification code.',tip3Title:'Verify separately',tip3Text:'Call the person or company using a number you already trust.',settingsTitle:'Trusted person',settingsIntro:'Add someone you trust. SafeCircle can prepare a text, email, or WhatsApp message asking them to review a suspicious message.',nameLabel:'Name',phoneLabel:'Phone number',emailLabel:'Email',shareTitle:'Ask someone you trust',shareIntro:'Choose how you want to send the message and safety report.',high:'Likely a scam',medium:'Be careful',low:'No strong scam signs found',highSummary:'Do not reply, click links, send money, or share personal information.',mediumSummary:'Some parts of this message need verification before you act.',lowSummary:'We did not find strong warning signs, but you should still verify unexpected requests.',safeAction1:'Do not reply or click any links yet.',safeAction2:'Contact the person or organization using a trusted number or official website.',safeAction3:'Ask someone you trust to review the message.',noSigns:'No common scam patterns were detected.',needText:'Please paste or speak a message first.',copied:'Copied to clipboard.',analyzing:'Reading text from the screenshot…',ocrFail:'We could not read this image. Please paste or type the message instead.'},
 es:{pageTitle:'¿Es seguro este mensaje?',pageSubtitle:'Pega un texto, correo o mensaje sospechoso. SafeCircle explica las señales en palabras sencillas.',missionText:'Protección accesible contra estafas',languageLabel:'Idioma',settingsButton:'Persona de confianza',inputTitle:'Agrega el mensaje sospechoso',sampleButton:'Probar un ejemplo',messageLabel:'Texto del mensaje',privacyNote:'El mensaje se analiza en este dispositivo y no se guarda.',voiceButton:'🎙 Dictar mensaje',clearButton:'Borrar',checkButton:'Revisar este mensaje',resultHeading:'Resultado de seguridad',signsHeading:'Señales de alerta',actionsHeading:'Qué hacer ahora',readButton:'🔊 Leer en voz alta',trustedButton:'Preguntar a mi persona de confianza',copyButton:'Copiar informe',disclaimer:'SafeCircle ofrece orientación, no una garantía. Contacta a la organización usando un número o sitio que encuentres por tu cuenta.',learnTitle:'Pausa antes de actuar',tip1Title:'Ve despacio',tip1Text:'Los estafadores crean urgencia para que actúes sin pensar.',tip2Title:'Protege tus códigos',tip2Text:'Nunca compartas contraseñas, PIN ni códigos de verificación.',tip3Title:'Verifica por separado',tip3Text:'Llama a la persona o empresa usando un número confiable.',high:'Probablemente es una estafa',medium:'Ten cuidado',low:'No se encontraron señales fuertes',highSummary:'No respondas, abras enlaces, envíes dinero ni compartas información.',mediumSummary:'Hay partes que debes verificar antes de actuar.',lowSummary:'No encontramos señales fuertes, pero verifica cualquier solicitud inesperada.',safeAction1:'No respondas ni abras enlaces todavía.',safeAction2:'Contacta a la persona u organización con un número confiable.',safeAction3:'Pide a alguien de confianza que revise el mensaje.',noSigns:'No se detectaron patrones comunes de estafa.',needText:'Primero pega o dicta un mensaje.',copied:'Copiado.',analyzing:'Leyendo el texto de la imagen…',ocrFail:'No pudimos leer la imagen. Escribe o pega el mensaje.'},
 hi:{pageTitle:'क्या यह संदेश सुरक्षित है?',pageSubtitle:'संदिग्ध टेक्स्ट, ईमेल या सोशल मीडिया संदेश यहाँ चिपकाएँ। SafeCircle सरल भाषा में खतरे बताएगा।',missionText:'सभी के लिए आसान सुरक्षा',languageLabel:'भाषा',settingsButton:'विश्वसनीय व्यक्ति',inputTitle:'संदिग्ध संदेश जोड़ें',sampleButton:'उदाहरण देखें',messageLabel:'संदेश',privacyNote:'संदेश इसी डिवाइस पर जाँचा जाता है और सेव नहीं होता।',voiceButton:'🎙 बोलकर लिखें',clearButton:'साफ करें',checkButton:'संदेश जाँचें',resultHeading:'सुरक्षा परिणाम',signsHeading:'मिले हुए चेतावनी संकेत',actionsHeading:'अब क्या करें',readButton:'🔊 परिणाम सुनें',trustedButton:'विश्वसनीय व्यक्ति से पूछें',copyButton:'रिपोर्ट कॉपी करें',disclaimer:'SafeCircle केवल मार्गदर्शन देता है, गारंटी नहीं। संस्था से उसके आधिकारिक नंबर या वेबसाइट द्वारा संपर्क करें।',learnTitle:'कदम उठाने से पहले रुकें',tip1Title:'जल्दी न करें',tip1Text:'ठग जल्दबाजी करवाते हैं ताकि आप सोच न सकें।',tip2Title:'कोड सुरक्षित रखें',tip2Text:'पासवर्ड, PIN या OTP कभी साझा न करें।',tip3Title:'अलग तरीके से पुष्टि करें',tip3Text:'व्यक्ति या कंपनी को भरोसेमंद नंबर से कॉल करें।',high:'यह संभवतः धोखा है',medium:'सावधान रहें',low:'मजबूत धोखाधड़ी संकेत नहीं मिले',highSummary:'जवाब न दें, लिंक न खोलें, पैसे या निजी जानकारी न भेजें।',mediumSummary:'कार्रवाई से पहले कुछ बातों की पुष्टि करें।',lowSummary:'मजबूत संकेत नहीं मिले, फिर भी अनपेक्षित अनुरोध की पुष्टि करें।',safeAction1:'अभी जवाब न दें और लिंक न खोलें।',safeAction2:'भरोसेमंद नंबर या आधिकारिक वेबसाइट से संपर्क करें।',safeAction3:'किसी विश्वसनीय व्यक्ति से संदेश जाँचने को कहें।',noSigns:'सामान्य धोखाधड़ी पैटर्न नहीं मिले।',needText:'पहले संदेश लिखें या बोलें।',copied:'कॉपी हो गया।',analyzing:'तस्वीर से टेक्स्ट पढ़ा जा रहा है…',ocrFail:'तस्वीर पढ़ी नहीं जा सकी। संदेश टाइप या पेस्ट करें।'},
 te:{pageTitle:'ఈ సందేశం సురక్షితమేనా?',pageSubtitle:'అనుమానాస్పద టెక్స్ట్, ఈమెయిల్ లేదా సోషల్ మీడియా సందేశాన్ని ఇక్కడ పెట్టండి. SafeCircle సులభమైన మాటల్లో ప్రమాద సూచనలు చెబుతుంది.',missionText:'అందరికీ అందుబాటులో భద్రత',languageLabel:'భాష',settingsButton:'నమ్మకమైన వ్యక్తి',inputTitle:'అనుమానాస్పద సందేశాన్ని జోడించండి',sampleButton:'ఉదాహరణ చూడండి',messageLabel:'సందేశం',privacyNote:'సందేశం ఈ పరికరంలోనే పరిశీలించబడుతుంది; సేవ్ చేయబడదు.',voiceButton:'🎙 మాట్లాడి నమోదు చేయండి',clearButton:'తుడిచివేయి',checkButton:'సందేశాన్ని తనిఖీ చేయి',resultHeading:'భద్రతా ఫలితం',signsHeading:'కనిపించిన హెచ్చరికలు',actionsHeading:'ఇప్పుడు ఏమి చేయాలి',readButton:'🔊 ఫలితాన్ని వినండి',trustedButton:'నమ్మకమైన వ్యక్తిని అడగండి',copyButton:'రిపోర్ట్ కాపీ చేయి',disclaimer:'SafeCircle మార్గదర్శకత్వం మాత్రమే ఇస్తుంది; హామీ కాదు. అధికారిక నంబర్ లేదా వెబ్‌సైట్ ద్వారా సంస్థను సంప్రదించండి.',learnTitle:'చర్య తీసుకునే ముందు ఆగండి',tip1Title:'తొందరపడవద్దు',tip1Text:'ఆలోచించకుండా చర్య తీసుకునేలా మోసగాళ్లు తొందర పెడతారు.',tip2Title:'కోడ్‌లను కాపాడండి',tip2Text:'పాస్‌వర్డ్, PIN లేదా OTP ఎప్పుడూ పంచుకోవద్దు.',tip3Title:'వేరే మార్గంలో నిర్ధారించండి',tip3Text:'మీకు తెలిసిన నంబర్‌తో వ్యక్తి లేదా సంస్థకు కాల్ చేయండి.',high:'ఇది మోసం అయ్యే అవకాశం ఎక్కువ',medium:'జాగ్రత్తగా ఉండండి',low:'బలమైన మోసం సూచనలు కనిపించలేదు',highSummary:'జవాబు ఇవ్వవద్దు, లింక్ తెరవవద్దు, డబ్బు లేదా వ్యక్తిగత సమాచారం పంపవద్దు.',mediumSummary:'చర్యకు ముందు కొన్ని విషయాలను నిర్ధారించాలి.',lowSummary:'బలమైన సూచనలు లేవు, అయినా అనుకోని అభ్యర్థనలను నిర్ధారించండి.',safeAction1:'ఇప్పుడే జవాబు ఇవ్వవద్దు లేదా లింక్ తెరవవద్దు.',safeAction2:'నమ్మకమైన నంబర్ లేదా అధికారిక వెబ్‌సైట్ ద్వారా సంప్రదించండి.',safeAction3:'నమ్మకమైన వ్యక్తితో సందేశాన్ని పరిశీలించండి.',noSigns:'సాధారణ మోసం నమూనాలు కనిపించలేదు.',needText:'ముందుగా సందేశాన్ని టైప్ చేయండి లేదా మాట్లాడండి.',copied:'కాపీ అయింది.',analyzing:'చిత్రం నుంచి వచనం చదువుతోంది…',ocrFail:'చిత్రాన్ని చదవలేకపోయాం. సందేశాన్ని టైప్ చేయండి.'}
};
const rules=[
 {id:'urgency',weight:15,re:/\b(urgent|immediately|right now|act now|today only|within \d+ (minutes?|hours?)|expire[sd]?|final warning|asap|hurry)\b/i,text:'The message creates urgency or a very short deadline.'},
 {id:'threat',weight:18,re:/\b(arrest|warrant|police|legal action|suspend(ed)?|close(d)? your account|locked|penalty|fine|deport|tax debt)\b/i,text:'It uses threats or fear to pressure you.'},
 {id:'payment',weight:22,re:/\b(gift card|bitcoin|crypto(currency)?|wire transfer|western union|moneygram|cash app|zelle|venmo|payment|pay now|send money|bank transfer)\b/i,text:'It asks for money or a hard-to-reverse payment.'},
 {id:'secret',weight:17,re:/\b(do not tell|don't tell|keep (this )?secret|between us|confidential|do not contact)\b/i,text:'It asks you to keep the request secret.'},
 {id:'credentials',weight:25,re:/\b(password|passcode|pin|one[- ]?time code|otp|verification code|security code|login details|social security|ssn)\b/i,text:'It asks for a password, code, or sensitive personal information.'},
 {id:'link',weight:10,re:/(https?:\/\/|www\.|\b[a-z0-9-]+\.(zip|top|click|xyz|info|live|site|online|work)\b)/i,text:'It contains a link that may not belong to the real organization.'},
 {id:'impersonation',weight:16,re:/\b(i am your (son|daughter|grandson|granddaughter)|new phone|boss here|ceo|bank security|irs|social security administration|microsoft support|tech support|package delivery)\b/i,text:'The sender may be impersonating a relative, company, or authority.'},
 {id:'prize',weight:16,re:/\b(congratulations|winner|won a prize|lottery|claim your reward|free money|inheritance|refund waiting)\b/i,text:'It promises an unexpected prize, reward, or refund.'},
 {id:'remote',weight:20,re:/\b(anydesk|teamviewer|remote access|screen share|install this app|download this app)\b/i,text:'It asks for remote access or installation of unfamiliar software.'},
 {id:'attachment',weight:8,re:/\b(open the attachment|download the file|invoice attached|see attached)\b/i,text:'It pushes you to open an unexpected file or attachment.'}
];
const samples=[
 'URGENT: Your bank account will be locked within 30 minutes. Verify your password and one-time code now at http://secure-bank-login.xyz',
 'Hi Grandma, I lost my phone. This is my new number. Please do not tell Mom. I need $500 in gift cards right now.',
 'Your package is scheduled for delivery tomorrow between 2 PM and 4 PM. Track it using the official carrier app.'
];
function t(){return translations[els.language.value]||translations.en}
function applyLanguage(){const x=t();Object.keys(x).forEach(k=>{const el=$(k);if(el)el.textContent=x[k]});els.message.placeholder=els.language.value==='en'?'Paste the message here…':'';document.documentElement.lang=els.language.value;localStorage.setItem('safecircle-language',els.language.value);if(lastResult)renderResult(lastResult)}
function analyze(text){let score=0;const findings=[];for(const rule of rules){if(rule.re.test(text)){score+=rule.weight;findings.push(rule.text)}}const exclamations=(text.match(/!/g)||[]).length;if(exclamations>=3){score+=8;findings.push('It uses repeated exclamation marks to increase pressure.')}if(/\b(dear customer|dear user|dear account holder)\b/i.test(text)){score+=6;findings.push('It uses a generic greeting instead of your name.')}if(/\b(kindly|dear beneficiary)\b/i.test(text)){score+=5;findings.push('The wording is commonly used in mass scam messages.')}score=Math.min(100,score);let level=score>=45?'high':score>=20?'medium':'low';return{score,level,findings,text}}
function localizedFindings(result){if(els.language.value==='en')return result.findings;const generic={es:['El mensaje crea urgencia o presión.','Solicita dinero o información sensible.','Puede incluir un enlace o identidad que debe verificarse.'],hi:['संदेश जल्दबाजी या दबाव बनाता है।','यह पैसे या संवेदनशील जानकारी माँग सकता है।','लिंक या पहचान की अलग से पुष्टि करनी चाहिए।'],te:['సందేశం తొందర లేదా ఒత్తిడి సృష్టిస్తోంది.','డబ్బు లేదా సున్నితమైన సమాచారం అడగవచ్చు.','లింక్ లేదా వ్యక్తి నిజమో వేరే మార్గంలో నిర్ధారించాలి.']};return result.findings.length?generic[els.language.value].slice(0,Math.min(3,result.findings.length)):[]}
function renderResult(result){lastResult=result;const x=t(),level=result.level;els.banner.className=`risk-banner risk-${level}`;els.riskIcon.textContent=level==='high'?'!':level==='medium'?'?':'✓';els.riskLabel.textContent=x[level];els.riskSummary.textContent=x[`${level}Summary`];els.riskScore.textContent=`${result.score}/100`;els.warnings.innerHTML='';const list=localizedFindings(result);(list.length?list:[x.noSigns]).forEach(v=>{const li=document.createElement('li');li.textContent=v;els.warnings.appendChild(li)});els.actions.innerHTML='';[x.safeAction1,x.safeAction2,x.safeAction3].forEach(v=>{const li=document.createElement('li');li.textContent=v;els.actions.appendChild(li)});els.result.hidden=false;setTimeout(()=>els.result.scrollIntoView({behavior:'smooth',block:'start'}),50)}
function check(){const text=els.message.value.trim();if(!text){showToast(t().needText);els.message.focus();return}renderResult(analyze(text))}
function reportText(){if(!lastResult)return'';const x=t();return `SafeCircle: ${x[lastResult.level]} (${lastResult.score}/100)\n\n${x[`${lastResult.level}Summary`]}\n\n${x.signsHeading}:\n- ${(localizedFindings(lastResult).length?localizedFindings(lastResult):[x.noSigns]).join('\n- ')}\n\n${x.actionsHeading}:\n1. ${x.safeAction1}\n2. ${x.safeAction2}\n3. ${x.safeAction3}\n\nMessage checked:\n${lastResult.text}`}
function showToast(msg){els.toast.textContent=msg;els.toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.hidden=true,2600)}
async function copyText(text){try{await navigator.clipboard.writeText(text);showToast(t().copied)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();showToast(t().copied)}}
function readResult(){if(!lastResult)return;window.speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(reportText());utter.lang={en:'en-US',es:'es-US',hi:'hi-IN',te:'te-IN'}[els.language.value];window.speechSynthesis.speak(utter)}
function setupRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){els.voice.disabled=true;els.voice.title='Speech recognition is not supported in this browser.';return}recognition=new SR();recognition.interimResults=true;recognition.continuous=false;recognition.onresult=e=>{els.message.value=Array.from(e.results).map(r=>r[0].transcript).join(' ');updateCount()};recognition.onend=()=>{els.voice.setAttribute('aria-pressed','false');els.voice.textContent=t().voiceButton};recognition.onerror=()=>showToast('Microphone could not be started.');els.voice.addEventListener('click',()=>{recognition.lang={en:'en-US',es:'es-US',hi:'hi-IN',te:'te-IN'}[els.language.value];recognition.start();els.voice.setAttribute('aria-pressed','true');els.voice.textContent='■ Stop listening'})}
async function handleFile(file){if(!file)return;els.status.textContent='';if(file.type==='text/plain'){els.message.value=await file.text();updateCount();return}els.preview.src=URL.createObjectURL(file);els.preview.hidden=false;els.status.textContent=t().analyzing;try{if(!window.Tesseract)throw new Error('OCR unavailable');const result=await Tesseract.recognize(file,els.language.value==='en'?'eng':els.language.value==='es'?'spa':els.language.value==='hi'?'hin':'tel',{logger:m=>{if(m.status==='recognizing text')els.status.textContent=`${t().analyzing} ${Math.round((m.progress||0)*100)}%`}});els.message.value=result.data.text.trim();updateCount();els.status.textContent=els.message.value?'Text added. Review it, then check the message.':t().ocrFail}catch(err){console.error(err);els.status.textContent=t().ocrFail}}
function updateCount(){ $('charCount').textContent=`${els.message.value.length} / 8000` }
function openSettings(){$('contactName').value=localStorage.getItem('trusted-name')||'';$('contactPhone').value=localStorage.getItem('trusted-phone')||'';$('contactEmail').value=localStorage.getItem('trusted-email')||'';$('settingsDialog').showModal()}
function saveSettings(e){e.preventDefault();localStorage.setItem('trusted-name',$('contactName').value.trim());localStorage.setItem('trusted-phone',$('contactPhone').value.trim());localStorage.setItem('trusted-email',$('contactEmail').value.trim());$('settingsDialog').close();showToast('Trusted person saved.')}
function openShare(){if(!lastResult){check();if(!lastResult)return}const name=localStorage.getItem('trusted-name')||'there',phone=(localStorage.getItem('trusted-phone')||'').replace(/[^\d+]/g,''),email=localStorage.getItem('trusted-email')||'';const body=`Hi ${name}, I received a message that may be a scam. Could you review it before I respond?\n\n${reportText()}`;$('smsLink').href=phone?`sms:${phone}?&body=${encodeURIComponent(body)}`:'#';$('emailLink').href=email?`mailto:${email}?subject=${encodeURIComponent('Please review this suspicious message')}&body=${encodeURIComponent(body)}`:`mailto:?subject=${encodeURIComponent('Please review this suspicious message')}&body=${encodeURIComponent(body)}`;$('whatsappLink').href=`https://wa.me/${phone.replace('+','')}?text=${encodeURIComponent(body)}`;$('smsLink').classList.toggle('disabled',!phone);$('missingContact').textContent=!phone&&!email?'No contact is saved yet. You can still copy the message, or add a trusted person in settings.':'';$('copyShareButton').onclick=()=>copyText(body);$('shareDialog').showModal()}
els.check.addEventListener('click',check);els.message.addEventListener('input',updateCount);els.message.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')check()});$('clearButton').addEventListener('click',()=>{els.message.value='';els.result.hidden=true;lastResult=null;els.preview.hidden=true;els.status.textContent='';updateCount();els.message.focus()});$('sampleButton').addEventListener('click',()=>{els.message.value=samples[sampleIndex++%samples.length];updateCount();els.message.focus()});els.file.addEventListener('change',e=>handleFile(e.target.files[0]));els.copy.addEventListener('click',()=>copyText(reportText()));els.read.addEventListener('click',readResult);els.trusted.addEventListener('click',openShare);$('settingsButton').addEventListener('click',openSettings);$('settingsForm').addEventListener('submit',saveSettings);$('closeShare').addEventListener('click',()=>$('shareDialog').close());$('aboutButton').addEventListener('click',()=>$('aboutDialog').showModal());$('closeAbout').addEventListener('click',()=>$('aboutDialog').close());els.language.addEventListener('change',applyLanguage);els.language.value=localStorage.getItem('safecircle-language')||'en';applyLanguage();setupRecognition();updateCount();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));